@baseURL = http://localhost:3000/api
# Categories

# @name getAllCategories
GET {{baseURL}}/categories

####

# @name addNewCategory

POST {{baseURL}}/categories
Content-Type: application/json

{
    "name": "Jfold 3"
}

###
# @name updateCategory

PATCH http://localhost:3000/api/categories/2
Content-Type: application/json

{
    "name": "Fixel 4"
}

###
# @name removeCategory

DELETE  http://localhost:3000/api/categories/2